version: "3"
services:
  zlm-server-12345:
    image: zlmediakit/zlmediakit:master
    # ports:
    #   - "1935:1935"
    #   - "8554:554"
    #   - "8080:80"
    #   - "8443:443"
    #   - "10000:10000"
    #   - "8000:8000/udp"
    #   - "9000:9000/udp"
    #   - "10000:10000/udp"
    restart: always
    volumes:
      - ./conf:/opt/media/conf

  job_register_all_cameras:
    build:
      context: ./jobs/register_all_cameras
      dockerfile: Dockerfile
    restart: on-failure
    environment:
      - COOLDOWN_SECOND=5
      - DEPLOY_MODE=docker
    volumes:
      - ./conf/config.ini:/app/conf/config.ini:ro
      - ./jobs/register_all_cameras/conf/config.yaml:/app/conf/config.yaml:ro
      # - ./jobs/register_all_cameras:/app
    depends_on:
      - zlm-server-12345

  job_health_monitor-12345:
    build: ./jobs/health_monitor
    restart: on-failure
    environment:
      - COOLDOWN_SECOND=3600
      - DEPLOY_MODE=docker
    depends_on:
      - zlm-server-12345
    volumes:
      - ./conf/config.ini:/app/conf/config.ini:ro
      - ./jobs/health_monitor/conf/config.yaml:/app/conf/config.yaml:ro
